SUITE_NAME	LANrev Application 3.0

Applications/Enterprise/Enterprise.scp
Applications/Enterprise/EnterpriseDetail.scp
Applications/Enterprise/InstallEnterpriseApplication.scp
Applications/Enterprise/InstallEnterpriseApplicationInDetail.scp
Applications/Enterprise/InstallAllApplication.scp
Applications/Enterprise/AutoInstallation.scp

Applications/AppStore/GooglePlay.scp
Applications/AppStore/GooglePlayDetail.scp
Applications/AppStore/ViewGooglePlay.scp
Applications/AppStore/ViewGooglePlayInDetail.scp

Profiles/ProfileAvailable.scp
Profiles/ProfileAvailableDetail.scp
Profiles/InstallProfileAvailable.scp
Profiles/RemoveProfile.scp
Profiles/InstallProfileAvailableInDetail.scp
Profiles/AutoInstalledProfile.scp

Messages/CheckMessagesContent.scp
Messages/ClearMessageSelected.scp
Messages/ClearAllMessages.scp

Updates/ItemUpdate.scp
Updates/ItemUpdateDetail.scp
Updates/UpdateItem.scp
Updates/UpdateAllItem.scp



